---
- name: Add Datadog CentOS repo
  copy:
    dest: /etc/yum.repos.d/datadog.repo
    content: |
      [datadog]
      name = Datadog, Inc.
      baseurl = https://yum.datadoghq.com/stable/6/x86_64/
      enabled=1
      gpgcheck=1
      gpgkey=https://yum.datadoghq.com/DATADOG_RPM_KEY.public
             https://yum.datadoghq.com/DATADOG_RPM_KEY_E09422B3.public

  register: repo

- name: Install Datadog Agent
  yum:
    name: datadog-agent
    state: present
    update_cache: "{{ repo is changed }}"

- name: Add dd-agent user to docker group
  user:
    name: dd-agent
    groups: docker
    append: yes

- name: Datadog Agent config
  template:
    src: datadog.yaml.j2
    dest: /etc/datadog-agent/datadog.yaml
    owner: dd-agent
    group: dd-agent
  notify: restart dd-agent

- name: Datadog Agent config docker daemon
  template:
    src: docker-daemon.yaml.j2
    dest: /etc/datadog-agent/conf.d/docker.d/docker_daemon.yaml
    owner: dd-agent
    group: dd-agent
  notify: restart dd-agent