---

- name: restart flood
  docker_container:
    name: flood
    image: romancin/rutorrent-flood:latest
    state: started
    restart: yes
    env:
        UID: "991"
        GID: "991"
    volumes:
      - "{{ flood_download }}:/downloads"
      - "{{ flood_config }}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p
