---

- name: Launch Rtorrent-Flood
  docker_container:
    name: flood
    image: romancin/rutorrent-flood:latest
    state: started
    tty: yes
    cpu_shares: 1024
    env:
        PUID: "991"
        PGID: "991"
    volumes:
      - "{{ flood_download }}:/downloads"
      - "{{ flood_config }}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p

- name: Disable HTTPS for container's NGinx
  template:
    src: nginx.j2
    dest: "{{ flood_config }}/nginx/nginx.conf"
    owner: p2p
    group: p2p
  register: nginx_conf

- debug: var=nginx_conf

- name: Apply Nginx conf
  notify: restart flood
  when: nginx_conf is changed
  meta: flush_handlers



# - name: Directories hierarchy
#   file:
#     path: "/etc/{{ item }}"
#     state: directory
#   with_items:
#     - radarr
#     - sonarr
#     - jackett
#     - ombi
#     - tautulli

- name: Plex
  docker_container:
    name: plex
    image: plexinc/pms-docker
    state: started
    hostname: "{{ hostname }}"
    cpu_shares: 2048
    env:
        PLEX_UID: "992"
        PLEX_GID: "991"
        PLEX_CLAIM: "{{ plex_claim_token }}"
        ADVERTISE_IP: "{{ ansible_host }}"
    volumes:
      - "{{ plex_movies }}:/data/movies"
      - "{{ plex_tv }}:/data/tv"
      - "/var/lib/plex/transcode:/transcode"
      - "{{ plex_config }}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p


- name: Radarr
  docker_container:
    name: radarr
    image: linuxserver/radarr:latest
    state: started
    cpu_shares: 1024
    # restart: yes
    # recreate: yes
    volumes:
      - "/etc/radarr:/config"
      - "{{ flood_download }}/movies:/downloads"
      - "{{ plex_movies }}:/movies"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "991"
        PGID: "991"
    networks:
      - name: p2p
        links:
          - plex:plex

- name: Sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    state: started
    cpu_shares: 1024
    # restart: yes
    volumes:
      - "/etc/sonarr:/config"
      - "{{ flood_download }}/series:/downloads"
      - "{{ plex_tv }}:/tv"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "991"
        PGID: "991"
    networks:
      - name: p2p
        links:
          - plex:plex

- name: Jackett
  docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    state: started
    cpu_shares: 1024
    # restart: yes
    volumes:
      - "/etc/jackett:/config/Jackett"
      - "{{ torrent_blackhole }}:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "991"
        PGID: "991"
    ports:
      - "9117:9117"
    # networks:
    #   - name: p2p

- name: Tautulli
  docker_container:
    name: tautulli
    image: tautulli/tautulli:latest
    state: started
    cpu_shares: 1024
    # restart: yes
    volumes:
      - "/etc/tautulli:/config"
      - "{{ plex_config }}/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "991"
        PGID: "991"
    networks:
      - name: p2p

- name: Ombi
  docker_container:
    name: ombi
    image: linuxserver/ombi:latest
    state: started
    cpu_shares: 1024
    # restart: yes
    volumes:
      - "/etc/ombi:/config"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        PUID: "991"
        PGID: "991"
    networks:
      - name: p2p
        links:
          - plex:plex
          - sonarr:sonarr
          - radarr:radarr

- name: Caddyfile
  template:
    src: caddyfile.j2
    dest: /etc/Caddyfile

- name: Reverse-Proxy
  docker_container:
    name: reverse-proxy
    image: abiosoft/caddy
    state: started
    cpu_shares: 1024
    restart: yes
    # restart_policy: on-failure
    volumes:
      - "/etc/Caddyfile:/etc/Caddyfile"
      # - "/var/caddy/srv:/var/www/html"
      - "/etc/caddy/certs:/root/.caddy"
      - "/etc/localtime:/etc/localtime:ro"
    env:
        ACME_AGREE: true
    ports:
      - "80:80"
      - "443:2015"
    networks:
      - name: p2p
        links:
          - flood:flood
          - radarr:radarr
          - sonarr:sonarr
          - jackett:jackett
          - plex:plex
          - tautulli:tautulli
          - ombi:ombi