---
- name: Bazarr
  docker_container:
    name: bazarr
    image: linuxserver/bazarr:latest
    state: started
    hostname: bazarr
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    cpu_shares: 128
    env:
      PUID: "{{ p2p_uid }}"
      PGID: "{{ group_gid }}"
    volumes:
      - "{{ plex_movies }}:/movies"
      - "{{ plex_tv }}:/tv"
      - "{{ bazarr_config }}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    purge_networks: yes
    networks:
      - name: p2p
        links:
          - sonarr:sonarr
          - radarr:radarr
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"
      # http router
      traefik.http.routers.bazarr-http.rule: "Host(`bazarr.{{ domain }}`)"
      traefik.http.routers.bazarr-http.entrypoints: "web"
      traefik.http.routers.bazarr-http.service: "bazarr"
      # https router
      traefik.http.routers.bazarr-https.rule: "Host(`bazarr.{{ domain }}`)"
      traefik.http.routers.bazarr-https.entrypoints: "websecure"
      traefik.http.routers.bazarr-https.service: "bazarr"
      traefik.http.routers.bazarr-https.tls: "true"
      traefik.http.routers.bazarr-https.tls.certresolver: "cloudflare"
