---
- name: Caddyfile
  template:
    src: caddy/caddyfile.j2
    dest: /etc/Caddyfile

- name: Caddy
  docker_container:
    name: caddy
    image: abiosoft/caddy:latest
    state: started
    hostname: caddy
    pull: yes
    restart_policy: unless-stopped
    volumes:
      - "/etc/Caddyfile:/etc/Caddyfile"
      - "{{ exposed_folder }}:/var/www/files/others"
      - "{{ plex_movies }}:/var/www/files/movies"
      - "{{ plex_tv }}:/var/www/files/tv"
      - "/etc/localtime:/etc/localtime:ro"
    purge_networks: yes
    networks:
      - name: p2p
    labels:
      traefik.docker.network: "p2p"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:files.{{ domain }}"
      traefik.basic.port: "8080"
      traefik.frontend.auth.basic.users: "{{ files_basicauth_user }}:{{ files_basicauth_password | password_hash('blowfish') }}"