---
# - file:
#     path: "{{ path }}"
#     state: directory
#   with_items:
#     - /etc/rtorrent
#     - /etc/rutorrent
#     - /usr/share/rutorrent
#   loop_control:
#     loop_var: path

# - name: Conf rtorrent
#   template:
#     src: rtorrent/rtorrent.rc.j2
#     dest: /etc/rtorrent/.rtorrent.rc

# - name: Conf rutorrent
#   template:
#     src: rtorrent/rutorrent_config.php.j2
#     dest: /etc/rutorrent/config.php

- name: Flood
  docker_container:
    name: flood
    image: xataz/rtorrent-flood:latest
    state: started
    hostname: flood
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    env:
      UID: "{{ p2p_uid }}"
      GID: "{{ group_gid }}"
      RTORRENT_SCGI: 54321    # WIP
    ports:
      - 45000:45000
      - 45000:45000/udp
    volumes:
    #   - "{{ rtorrent_config }}:/config/rtorrent"
    #   - /etc/rutorrent:/config/rutorrent/conf
    #   - /usr/share/rutorrent:/config/rutorrent/share
      - /var/rtorrent/sessions:/data/.session
      - "{{ rtorrent_downloads }}:/p2p/downloads"
    #   - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p
    labels:
      traefik.docker.network: "p2p"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:flood.{{ domain }}"
      # traefik.frontend.auth.basic.users: "{{ rutorrent_basicauth_user }}:{{ rutorrent_basicauth_password | password_hash('blowfish') }}"
      traefik.basic.port: "3000"