---
- name: Jackett
  docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    state: started
    hostname: jackett
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    cpu_shares: 128
    volumes:
      - "/etc/jackett:/config/Jackett"
      - "{{ torrent_blackhole }}:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      PUID: "{{ p2p_uid }}"
      PGID: "{{ group_gid }}"
    purge_networks: yes
    networks:
      - name: p2p
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.jackett.loadbalancer.server.port: "9117"
      # http router
      traefik.http.routers.jackett-http.rule: "Host(`jackett.{{ domain }}`)"
      traefik.http.routers.jackett-http.entrypoints: "web"
      traefik.http.routers.jackett-http.service: "jackett"
      # https router
      traefik.http.routers.jackett-https.rule: "Host(`jackett.{{ domain }}`)"
      traefik.http.routers.jackett-https.entrypoints: "websecure"
      traefik.http.routers.jackett-https.service: "jackett"
      traefik.http.routers.jackett-https.tls: "true"
      traefik.http.routers.jackett-https.tls.certresolver: "cloudflare"
