---
- file:
    path: /etc/lighttpd
    state: directory

- name: Conf Lighttpd
  template:
    src: lighttpd/lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
  register: lighttpd

- set_fact:
    restart_lighttpd: "yes"
  when: lighttpd is changed

- name: Lighttpd
  docker_container:
    name: lighttpd
    image: sebp/lighttpd:latest
    state: started
    hostname: lighttpd
    restart: "{{ restart_lighttpd }}"
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    cpu_shares: 128
    volumes:
      - "/var/www/lighttpd:/var/www/localhost"
      - "/etc/lighttpd:/etc/lighttpd"
      - "/etc/localtime:/etc/localtime:ro"
    purge_networks: yes
    networks:
      - name: p2p
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.lighttpd.loadbalancer.server.port: "8080"
      # http router
      traefik.http.routers.lighttpd-http.rule: "Host(`{{ domain }}`) || Host(`www.{{ domain }}`)"
      traefik.http.routers.lighttpd-http.entrypoints: "web"
      traefik.http.routers.lighttpd-http.service: "lighttpd"
      # https router
      traefik.http.routers.lighttpd-https.rule: "Host(`{{ domain }}`) || Host(`www.{{ domain }}`)"
      traefik.http.routers.lighttpd-https.entrypoints: "websecure"
      traefik.http.routers.lighttpd-https.service: "lighttpd"
      traefik.http.routers.lighttpd-https.tls: "true"
      traefik.http.routers.lighttpd-https.tls.certresolver: "cloudflare"
