---
- name: Netdata
  docker_container:
    name: netdata
    image: firehol/netdata:latest
    pull: yes
    state: started
    hostname: netdata
    restart_policy: on-failure
    restart_retries: 2
    capabilities: "SYS_PTRACE"
    env:
      PUID: "{{ netdata_uid }}"
      PGID: 989 # Docker GID for socket permissions
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: p2p
    labels:
      traefik.docker.network: "p2p"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:metrics.{{ domain }}"
      traefik.frontend.auth.basic.users: "{{ metrics_basicauth_user }}:{{ metrics_basicauth_password | password_hash('blowfish') }}"
      traefik.basic.port: "19999"