---
- name: Ombi
  docker_container:
    name: ombi
    image: linuxserver/ombi:latest
    state: started
    hostname: ombi
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    cpu_shares: 128
    volumes:
      - "/etc/ombi:/config"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      PUID: "{{ p2p_uid }}"
      PGID: "{{ group_gid }}"
    purge_networks: yes
    networks:
      - name: p2p
        links:
          - plex:plex
          - sonarr:sonarr
          - radarr:radarr
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.ombi.loadbalancer.server.port: "3579"
      # http router
      traefik.http.routers.ombi-http.rule: "Host(`ombi.{{ domain }}`)"
      traefik.http.routers.ombi-http.entrypoints: "web"
      traefik.http.routers.ombi-http.service: "ombi"
      # https router
      traefik.http.routers.ombi-https.rule: "Host(`ombi.{{ domain }}`)"
      traefik.http.routers.ombi-https.entrypoints: "websecure"
      traefik.http.routers.ombi-https.service: "ombi"
      traefik.http.routers.ombi-https.tls: "true"
      traefik.http.routers.ombi-https.tls.certresolver: "cloudflare"
