---
- name: Plex
  docker_container:
    name: plex
    image: plexinc/pms-docker:plexpass
    state: started
    hostname: plex
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    cpu_shares: 1024
    env:
      PLEX_UID: "{{ plex_uid }}"
      PLEX_GID: "{{ plex_uid }}"
      PLEX_CLAIM: "{{ plex_claim_token }}"
      ADVERTISE_IP: "https://plex.{{ domain }}/"
    volumes:
      - "{{ plex_movies }}:/data/movies"
      - "{{ plex_tv }}:/data/tv"
      - "{{ plex_transcode }}:/transcode"
      - "{{ plex_config }}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.plex.loadbalancer.server.port: "32400"
      # http router
      traefik.http.routers.plex-http.rule: "Host(`plex.{{ domain }}`)"
      traefik.http.routers.plex-http.entrypoints: "web"
      traefik.http.routers.plex-http.service: "plex"
      # https router
      traefik.http.routers.plex-https.rule: "Host(`plex.{{ domain }}`)"
      traefik.http.routers.plex-https.entrypoints: "websecure"
      traefik.http.routers.plex-https.service: "plex"
      traefik.http.routers.plex-https.tls: "true"
      traefik.http.routers.plex-https.tls.certresolver: "cloudflare"
      # tcp routeur for phone home over TLS
      traefik.tcp.routers.plex.rule: "HostSNI(`plex-tls.{{ domain }}`)"
      traefik.tcp.routers.plex.entrypoints: "plex"
      traefik.tcp.routers.plex.service: "plex"
