---
- name: Portainer
  docker_container:
    name: portainer
    image: portainer/portainer:latest
    hostname: portainer
    state: started
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/portainer:/data"
    purge_networks: yes
    networks:
      - name: p2p
    labels:
      traefik.docker.network: "p2p"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:portainer.{{ domain }}"
      traefik.basic.port: "9000"
      # Headers for CORS compliance (not very effective...)
      traefik.frontend.headers.customResponseHeaders: 'Access-Control-Allow-Origin: *||Access-Control-Allow-Methods: DELETE, POST, GET, OPTIONS||Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type||Access-Control-Max-Age:600'
      traefik.frontend.headers.browserXSSFilter: "true"