---
- file:
    path: "{{ path }}"
    state: directory
  with_items:
    - /etc/rtorrent
    - /var/rtorrent
    - /usr/share/rutorrent
  loop_control:
    loop_var: path

- name: Conf rtorrent
  template:
    src: rtorrent/rtorrent.rc.j2
    dest: /etc/rtorrent/.rtorrent.rc

- name: Conf rutorrent    # still necessary ??
  template:
    src: rtorrent/rutorrent_config.php.j2
    dest: /etc/rutorrent/config.php

- name: Rtorrent
  docker_container:
    name: rtorrent
    image: mondedie/rutorrent:latest
    state: started
    hostname: rtorrent
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    cpu_shares: 192
    env:
      UID: "{{ p2p_uid }}"
      GID: "{{ group_gid }}"
    ports:
      - 45000:45000
      - 45000:45000/udp
    volumes:
      - "{{ rtorrent_config }}:/config"
      - "/usr/share/rutorrent:/config/rutorrent/share"
      - "/var/rtorrent/sessions:/data/.session"
      - "{{ rtorrent_downloads }}:/p2p/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: p2p
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.rtorrent.loadbalancer.server.port: "8080"
      # basicauth middleware
      traefik.http.middlewares.rtorrent-auth.basicauth.users: "{{ rutorrent_basicauth_user }}:{{ rutorrent_basicauth_password | password_hash('blowfish') }}"
      # http router
      traefik.http.routers.rtorrent-http.rule: "Host(`rtorrent.{{ domain }}`)"
      traefik.http.routers.rtorrent-http.entrypoints: "web"
      traefik.http.routers.rtorrent-http.service: "rtorrent"
      traefik.http.routers.rtorrent-http.middlewares: "rtorrent-auth@docker"
      # https router
      traefik.http.routers.rtorrent-https.rule: "Host(`rtorrent.{{ domain }}`)"
      traefik.http.routers.rtorrent-https.entrypoints: "websecure"
      traefik.http.routers.rtorrent-https.service: "rtorrent"
      traefik.http.routers.rtorrent-https.middlewares: "rtorrent-auth@docker"
      traefik.http.routers.rtorrent-https.tls: "true"
      traefik.http.routers.rtorrent-https.tls.certresolver: "cloudflare"