---
- name: Sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    state: started
    hostname: sonarr
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    cpu_shares: 128
    volumes:
      - "/etc/sonarr:/config"
      - "{{ medias_root }}:/p2p"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      PUID: "{{ p2p_uid }}"
      PGID: "{{ group_gid }}"
    purge_networks: yes
    networks:
      - name: p2p
        links:
          - rtorrent:rtorrent
          - jackett:jackett
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
      # http router
      traefik.http.routers.sonarr-http.rule: "Host(`sonarr.{{ domain }}`)"
      traefik.http.routers.sonarr-http.entrypoints: "web"
      traefik.http.routers.sonarr-http.service: "sonarr"
      # https router
      traefik.http.routers.sonarr-https.rule: "Host(`sonarr.{{ domain }}`)"
      traefik.http.routers.sonarr-https.entrypoints: "websecure"
      traefik.http.routers.sonarr-https.service: "sonarr"
      traefik.http.routers.sonarr-https.tls: "true"
      traefik.http.routers.sonarr-https.tls.certresolver: "cloudflare"
