---
- name: Tautulli
  docker_container:
    name: tautulli
    image: tautulli/tautulli:latest
    state: started
    hostname: tautulli
    pull: yes
    restart_policy: on-failure
    restart_retries: 2
    purge_networks: yes
    cpu_shares: 128
    volumes:
      - "/etc/tautulli:/config"
      - "{{ plex_config }}/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      PUID: "{{ p2p_uid }}"
      PGID: "{{ group_gid }}"
    networks:
      - name: p2p
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.tautulli.loadbalancer.server.port: "8181"
      # http router
      traefik.http.routers.tautulli-http.rule: "Host(`tautulli.{{ domain }}`)"
      traefik.http.routers.tautulli-http.entrypoints: "web"
      traefik.http.routers.tautulli-http.service: "tautulli"
      # https router
      traefik.http.routers.tautulli-https.rule: "Host(`tautulli.{{ domain }}`)"
      traefik.http.routers.tautulli-https.entrypoints: "websecure"
      traefik.http.routers.tautulli-https.service: "tautulli"
      traefik.http.routers.tautulli-https.tls: "true"
      traefik.http.routers.tautulli-https.tls.certresolver: "cloudflare"
