---
- file:
    path: "/var/opt/thelounge"
    state: directory

- name: TheLounge
  docker_container:
    name: thelounge
    image: thelounge/thelounge:alpine
    state: started
    hostname: thelounge
    pull: yes
    restart_policy: unless-stopped
    purge_networks: yes
    cpu_shares: 128
    volumes:
      - /var/opt/thelounge:/var/opt/thelounge
      - /etc/localtime:/etc/localtime:ro
    networks:
      - name: p2p
    labels:
      traefik.enable: "true"
      traefik.docker.network: "p2p"
      # service
      traefik.http.services.thelounge.loadbalancer.server.port: "9000"
      # http router
      traefik.http.routers.thelounge-http.rule: "Host(`thelounge.{{ domain }}`)"
      traefik.http.routers.thelounge-http.entrypoints: "web"
      traefik.http.routers.thelounge-http.service: "thelounge"
      # https router
      traefik.http.routers.thelounge-https.rule: "Host(`thelounge.{{ domain }}`)"
      traefik.http.routers.thelounge-https.entrypoints: "websecure"
      traefik.http.routers.thelounge-https.service: "thelounge"
      traefik.http.routers.thelounge-https.tls: "true"
      traefik.http.routers.thelounge-https.tls.certresolver: "cloudflare"
