---
- name: Ensuring group 'wheel' exists
  group:
    name: "wheel"
    state: present

- name: "Ensuring group '{{ group_name }}' exists"
  group:
    name: "{{ group_name }}"
    state: present
    gid: "{{ group_gid }}"

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Creating users
  user: 
    name: "{{ item.name }}"
    groups: "{{ item.groups}} "
    append: "{{ item.append}}"
    state: present
    createhome: "{{ item.createhome }}"
    uid: "{{ item.uid }}"
  with_items:
    - { name: "deployer", groups: "wheel", append: yes, createhome: yes , uid: "1000" }
    - { name: "{{ p2p_user }}", groups: "{{ group_name }}", append: yes, createhome: no, uid: "{{ p2p_uid }}" }
    - { name: "{{ plex_user }}", groups: "{{ group_name }}", append: yes, createhome: no, uid: "{{ plex_uid }}" }

- name: Set up authorized keys for the deployer user
  authorized_key: 
    user: deployer 
    key: "{{ item }}"
  with_file:
    - "~/.ssh/id_rsa.pub"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: Install Packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - python2-pip

- name: Start dockerd
  service:
    name: docker
    state: started

- name: Install docker python interface
  pip:
    name: docker
