---

- name: Ensuring group 'wheel' exists
  group:
    name: "wheel"
    state: present

- name: Ensuring group 'p2p' exists
  group:
    name: "p2p"
    state: present
    gid: 991

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Creating users
  user: 
    name: "{{ item.name }}"
    groups: "{{ item.groups}} "
    append: "{{ item.append}}"
    state: present
    createhome: "{{ item.createhome }}"
    uid: "{{ item.uid }}"
  with_items:
    - { name: "deployer", groups: "wheel", append: yes, createhome: yes , uid: "1001" }
    - { name: "p2p", groups: "p2p", append: yes, createhome: no, uid: "991" }
    - { name: "plex", groups: "p2p", append: yes, createhome: no, uid: "992" }
    - { name: "flood", groups: "p2p", append: yes, createhome: no, uid: "993" }


- name: Set up authorized keys for the deployer user
  authorized_key: 
    user: deployer 
    key: "{{ item }}"
  with_file:
    - "~/.ssh/id_rsa.pub"

- name: Install Packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - docker
      - python2-pip

- name: Start dockerd
  service:
    name: docker
    state: started

- name: Install docker python interface
  pip:
    name: docker
